#############################################################################
# Makefile for building: MMReversi.app/Contents/MacOS/MMReversi
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  MMReversi.pro
# Template: app
# Command: /Users/benjaminschuch/Qt/5.3/clang_64/bin/qmake -o Makefile MMReversi.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.9 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.9 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../../Qt/5.3/clang_64/mkspecs/macx-clang -I. -I../../../../Qt/5.3/clang_64/lib/QtMultimedia.framework/Versions/5/Headers -I../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../../../Qt/5.3/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I../../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -F/Users/benjaminschuch/Qt/5.3/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.9
LIBS          = $(SUBLIBS) -F/Users/benjaminschuch/Qt/5.3/clang_64/lib -framework QtMultimedia -framework QtGui -framework QtCore -framework QtNetwork -framework QtWidgets -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/benjaminschuch/Qt/5.3/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		boardwidget.cpp \
		game.cpp \
		board.cpp \
		minimax.cpp \
		gamedialog.cpp \
		settings.cpp qrc_resources.cpp \
		moc_mainwindow.cpp \
		moc_boardwidget.cpp \
		moc_game.cpp \
		moc_board.cpp \
		moc_gamedialog.cpp \
		moc_settings.cpp
OBJECTS       = main.o \
		mainwindow.o \
		boardwidget.o \
		game.o \
		board.o \
		minimax.o \
		gamedialog.o \
		settings.o \
		qrc_resources.o \
		moc_mainwindow.o \
		moc_boardwidget.o \
		moc_game.o \
		moc_board.o \
		moc_gamedialog.o \
		moc_settings.o
DIST          = ../../../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.3/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../../../Qt/5.3/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.3/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.3/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.3/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.3/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/lex.prf \
		MMReversi.pro main.cpp \
		mainwindow.cpp \
		boardwidget.cpp \
		game.cpp \
		board.cpp \
		minimax.cpp \
		gamedialog.cpp \
		settings.cpp
QMAKE_TARGET  = MMReversi
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = MMReversi.app/Contents/MacOS/MMReversi

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.9 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile MMReversi.app/Contents/PkgInfo MMReversi.app/Contents/Resources/empty.lproj MMReversi.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h ui_gamedialog.h ui_settings.h $(OBJECTS)  
	@test -d MMReversi.app/Contents/MacOS/ || mkdir -p MMReversi.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MMReversi.pro ../../../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.3/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../../../Qt/5.3/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.3/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.3/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.3/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.3/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.3/clang_64/mkspecs/features/lex.prf \
		MMReversi.pro \
		resources.qrc \
		/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl \
		/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl
	$(QMAKE) -o Makefile MMReversi.pro
../../../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt/5.3/clang_64/mkspecs/qdevice.pri:
../../../../Qt/5.3/clang_64/mkspecs/features/device_config.prf:
../../../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf:
../../../../Qt/5.3/clang_64/mkspecs/common/unix.conf:
../../../../Qt/5.3/clang_64/mkspecs/common/mac.conf:
../../../../Qt/5.3/clang_64/mkspecs/common/macx.conf:
../../../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/5.3/clang_64/mkspecs/common/clang.conf:
../../../../Qt/5.3/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt/5.3/clang_64/mkspecs/qconfig.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/default_post.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/qt.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/resources.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/moc.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/uic.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/yacc.prf:
../../../../Qt/5.3/clang_64/mkspecs/features/lex.prf:
MMReversi.pro:
resources.qrc:
/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl:
/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MMReversi.pro

qmake_all: FORCE

MMReversi.app/Contents/PkgInfo: 
	@test -d MMReversi.app/Contents || mkdir -p MMReversi.app/Contents
	@$(DEL_FILE) MMReversi.app/Contents/PkgInfo
	@echo "APPL????" >MMReversi.app/Contents/PkgInfo
MMReversi.app/Contents/Resources/empty.lproj: 
	@test -d MMReversi.app/Contents/Resources || mkdir -p MMReversi.app/Contents/Resources
	@touch MMReversi.app/Contents/Resources/empty.lproj
	
MMReversi.app/Contents/Info.plist: 
	@test -d MMReversi.app/Contents || mkdir -p MMReversi.app/Contents
	@$(DEL_FILE) MMReversi.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.MMReversi,g" -e "s,@EXECUTABLE@,MMReversi,g" -e "s,@TYPEINFO@,????,g" ../../../../Qt/5.3/clang_64/mkspecs/macx-clang/Info.plist.app >MMReversi.app/Contents/Info.plist
dist: 
	@test -d .tmp/MMReversi1.0.0 || mkdir -p .tmp/MMReversi1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/MMReversi1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/MMReversi1.0.0/ && $(COPY_FILE) --parents mainwindow.h boardwidget.h game.h board.h minimax.h gamedialog.h settings.h .tmp/MMReversi1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp boardwidget.cpp game.cpp board.cpp minimax.cpp gamedialog.cpp settings.cpp .tmp/MMReversi1.0.0/ && $(COPY_FILE) --parents mainwindow.ui gamedialog.ui settings.ui .tmp/MMReversi1.0.0/ && (cd `dirname .tmp/MMReversi1.0.0` && $(TAR) MMReversi1.0.0.tar MMReversi1.0.0 && $(COMPRESS) MMReversi1.0.0.tar) && $(MOVE) `dirname .tmp/MMReversi1.0.0`/MMReversi1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MMReversi1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r MMReversi.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		highscore.qml \
		resources/green.png \
		resources/red.png \
		resources/gameover.wav \
		resources/win.wav \
		resources/doh.wav
	/Users/benjaminschuch/Qt/5.3/clang_64/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_boardwidget.cpp moc_game.cpp moc_board.cpp moc_gamedialog.cpp moc_settings.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_boardwidget.cpp moc_game.cpp moc_board.cpp moc_gamedialog.cpp moc_settings.cpp
moc_mainwindow.cpp: ../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		board.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		game.h \
		mainwindow.h
	/Users/benjaminschuch/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/benjaminschuch/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/benjaminschuch/Dropbox/Projekte/Qt/MMReversi -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtMultimedia.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/benjaminschuch/Qt/5.3/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_boardwidget.cpp: ../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		board.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		boardwidget.h
	/Users/benjaminschuch/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/benjaminschuch/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/benjaminschuch/Dropbox/Projekte/Qt/MMReversi -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtMultimedia.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/benjaminschuch/Qt/5.3/clang_64/lib boardwidget.h -o moc_boardwidget.cpp

moc_game.cpp: ../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		board.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		game.h
	/Users/benjaminschuch/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/benjaminschuch/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/benjaminschuch/Dropbox/Projekte/Qt/MMReversi -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtMultimedia.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/benjaminschuch/Qt/5.3/clang_64/lib game.h -o moc_game.cpp

moc_board.cpp: ../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		board.h
	/Users/benjaminschuch/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/benjaminschuch/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/benjaminschuch/Dropbox/Projekte/Qt/MMReversi -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtMultimedia.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/benjaminschuch/Qt/5.3/clang_64/lib board.h -o moc_board.cpp

moc_gamedialog.cpp: ../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		board.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		gamedialog.h
	/Users/benjaminschuch/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/benjaminschuch/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/benjaminschuch/Dropbox/Projekte/Qt/MMReversi -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtMultimedia.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/benjaminschuch/Qt/5.3/clang_64/lib gamedialog.h -o moc_gamedialog.cpp

moc_settings.cpp: ../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		settings.h
	/Users/benjaminschuch/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/benjaminschuch/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/benjaminschuch/Dropbox/Projekte/Qt/MMReversi -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtMultimedia.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/benjaminschuch/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/benjaminschuch/Qt/5.3/clang_64/lib settings.h -o moc_settings.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_gamedialog.h ui_settings.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_gamedialog.h ui_settings.h
ui_mainwindow.h: mainwindow.ui \
		boardwidget.h \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		board.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h
	/Users/benjaminschuch/Qt/5.3/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_gamedialog.h: gamedialog.ui
	/Users/benjaminschuch/Qt/5.3/clang_64/bin/uic gamedialog.ui -o ui_gamedialog.h

ui_settings.h: settings.ui
	/Users/benjaminschuch/Qt/5.3/clang_64/bin/uic settings.ui -o ui_settings.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		board.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		game.h \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		board.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		game.h \
		ui_mainwindow.h \
		boardwidget.h \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		gamedialog.h \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		settings.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../../../Qt/5.3/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/QSound \
		../../../../Qt/5.3/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/qsound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

boardwidget.o: boardwidget.cpp boardwidget.h \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		board.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		minimax.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o boardwidget.o boardwidget.cpp

game.o: game.cpp game.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		board.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		gamedialog.h \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game.o game.cpp

board.o: board.cpp board.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QCoreApplication \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qcoreapplication.h \
		../../../../Qt/5.3/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/QSound \
		../../../../Qt/5.3/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/qsound.h \
		minimax.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o board.o board.cpp

minimax.o: minimax.cpp minimax.h \
		board.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QCoreApplication \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qcoreapplication.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minimax.o minimax.cpp

gamedialog.o: gamedialog.cpp gamedialog.h \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		board.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		ui_gamedialog.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gamedialog.o gamedialog.cpp

settings.o: settings.cpp settings.h \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		ui_settings.h \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_boardwidget.o: moc_boardwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_boardwidget.o moc_boardwidget.cpp

moc_game.o: moc_game.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_game.o moc_game.cpp

moc_board.o: moc_board.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_board.o moc_board.cpp

moc_gamedialog.o: moc_gamedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gamedialog.o moc_gamedialog.cpp

moc_settings.o: moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settings.o moc_settings.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

